# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 779d61d08a8a6af7febbd5e0a2ef099fe97ee016a730ff4d321dd2214a2267e321887a5bc5b8c59d04ec67eb2abe798dd20a4909b71e4d63717718c34b677a8d

test:
  secret_key_base: b99e780bd65cd636f556a41ce24b72f4686f6353d6b82f6708e7301f491c5cbdb3bd97a4e5e1175267b483ee4d0fe0666062b9d7d913a9493e4fae4d35a59136

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
